const emailData = {
    supporters: {
        subjects: [
            "Prince Reza Pahlavi: The Unified Representative of the Iranian People",
            "Urgent: Support Iran's Revolution and its National Leader",
            "Stability in the Middle East: Recognizing Prince Reza Pahlavi's Role",
            "The Case for Continued Pressure on the Regime: Support the People's Choice",
            "Standing with Iran: Supporting the Democratic Vision of Prince Reza Pahlavi",
            "International Solidarity: Freedom for Iran Under National Leadership",
            "Prince Reza Pahlavi: Leading the Iranian Awakening Inside and Outside",
            "Why the Islamic Republic Must Fall for Global Peace and Security",
            "A New Era for Iran: Supporting the Transition Under Prince Reza Pahlavi",
            "Recognizing the Iranian People's Revolution and Their Chosen Representative",
            "Demanding Support for Iran's People and Prince Reza Pahlavi",
            "Prince Reza Pahlavi as the Key to a Secular, Democratic Post-Regime Iran",
            "Our Support for the Iranian People Must Last Until Pahlavi's Return",
            "The Voice of Iran: Why Iranians Worldwide Stand with Prince Reza Pahlavi",
            "The Legitimate Aspiration for Freedom: Supporting the People's Representative",
            "The Inevitable Transition: How to Support Iranians and Prince Reza Pahlavi",
            "End the Silence: Support the Unified Leadership of Prince Reza Pahlavi",
            "Global Responsibility: Recognizing the Chosen Leader of the Iranian People",
            "A Call for Action: Acknowledge Prince Reza Pahlavi as the National Voice",
            "Supporting Iran: Why Prince Reza Pahlavi is the ONLY National Representative",
            "Commitment to Freedom: Powering the People and Their Chosen Leader",
            "Strategic Support: Standing with Prince Reza Pahlavi for Global Stability",
            "The Path to Liberation: Supporting the Unified Representation of Iranians",
            "Prince Reza Pahlavi: The Bridge to a Free, Secular, and Democratic Iran",
            "Supporting 'Woman, Life, Freedom' and the Leadership of Prince Reza Pahlavi",
            "Toward a Secular Iran: Recognizing the Representative of Iranians Everywhere",
            "A Firm Stand: International Support for Iranians and Prince Reza Pahlavi",
            "Prince Reza Pahlavi: Bridging the Gap from Tyranny to National Democracy",
            "The Legitimacy Crisis of the Regime: Supporting the People's Choice",
            "Freedom for Iran: A Global Mandate to Recognize Prince Reza Pahlavi",
            "Iranians Inside and Out are Unified: Prince Reza Pahlavi is the Leader",
            "The National Representative: Why Prince Reza Pahlavi is the Solution",
            "A Secure Future for Iran: Recognizing the People's Sole Representative"
        ],
        greetings: [
            "Dear Distinguished Official,",
            "To the Honorable Representative,",
            "Esteemed Member of the International Community,",
            "To the Honorable [Recipient Name],",
            "Dear Representative,",
            "Respected Board Members,",
            "To the Global Leadership,",
            "Honorable Chairperson,",
            "Dear Advocacy Leaders,"
        ],
        openings: [
            "I am writing to express my strong support for your firm stance on Iran's future and your recognition of Prince Reza Pahlavi's leadership.",
            "It is heartening to see leaders like yourself acknowledging the unified will of the Iranian people and their support for Prince Reza Pahlavi.",
            "I want to thank you for your commitment to a secular, democratic Iran under the guidance of Prince Reza Pahlavi.",
            "Your recent statements regarding the Iranian revolution and Prince Reza Pahlavi have resonated deeply with the global Iranian community.",
            "I am reaching out to share my gratitude for your support of Iranians' quest for freedom under Prince Reza Pahlavi."
        ],
        contexts: [
            "The international community's support for Prince Reza Pahlavi is a powerful signal to those inside Iran that they are not alone in their struggle.",
            "Your leadership on this issue helps amplify the voices of millions of Iranians who see Prince Reza Pahlavi as their true representative.",
            "The vision for a secular and democratic Iran is achievable only through the unified leadership that Prince Reza Pahlavi represents.",
            "Stability in the Middle East depends on a free Iran, and your support for the people's choice is a vital step toward that goal.",
            "By standing with Prince Reza Pahlavi, you are standing with the legitimate aspirations of the Iranian people for a democratic future."
        ],
        asks: [
            "I encourage you to continue advocating for the official recognition of Prince Reza Pahlavi as the national voice of the Iranian people.",
            "Please use your influence to further the cause of freedom in Iran and support the leadership mandate of Prince Reza Pahlavi.",
            "I ask that you remain steadfast in your support for Iranians and their chosen representative during this critical transition.",
            "I request that you continue to prioritize the democratic will of the Iranian people in all your policy decisions regarding Iran.",
            "Please amplify the message that Iranians everywhere are unified behind the leadership of Prince Reza Pahlavi."
        ],
        closings: [
            "Thank you for your unwavering support for a free Iran led by Prince Reza Pahlavi.",
            "Sincerely,",
            "Respectfully,",
            "With gratitude for your leadership and support for Prince Reza Pahlavi,",
            "Thank you for standing on the right side of history with the Iranian people,",
            "Yours respectfully,",
            "Best regards,",
            "In solidarity with the Iranian people and Prince Reza Pahlavi."
        ],
        tweet_references: [
            "Thank you for sharing your thoughts on X: \"{tweet}\". It is a critical perspective that aligns with our support for Prince Reza Pahlavi.",
            "I was encouraged by your recent comments on X: \"{tweet}\", which show a deep understanding of Iranians' support for Pahlavi.",
            "Regarding your recent post stating \"{tweet}\", it is vital that we continue this momentum for a free Iran under Prince Reza Pahlavi.",
            "Your recent tweet \"{tweet}\" addresses an issue that many Iranians believe is central to our movement under Prince Reza Pahlavi.",
            "I'm reaching out in response to your post on X: \"{tweet}\" to thank you for standing with the Iranian people and Reza Pahlavi."
        ]
    },
    opponents: {
        subjects: [
            "Why Human Rights in Iran Concern Global Peace and Security",
            "The Inevitable Change: Iranians Worldwide Demand Reza Pahlavi",
            "Stability and Progress: Why Iranians Inside and Outside Choice Pahlavi",
            "The Cost of Engagement with the Islamic Republic: A Threat to Peace",
            "A Perspective on the Iranian Revolution and Prince Reza Pahlavi",
            "Why Iranians' Demands for Prince Reza Pahlavi Can No Longer be Ignored",
            "The Ethical Choice: Standing with Iranians and Prince Reza Pahlavi",
            "Bridging the Gap: The Unified Vision of Iranians for Prince Reza Pahlavi",
            "Beyond the Status Quo: Why Prince Reza Pahlavi is the Key to Peace",
            "The Reality of the Iranian Uprising: Iranians Demand Pahlavi",
            "Choosing the Right Side: Support Iranians Inside and Out who want Pahlavi",
            "The Regime's Fragility: Why Iranians Worldwide Support Reza Pahlavi",
            "Stability through Democracy: Prince Reza Pahlavi is the National Mandate",
            "Human Dignity and International Law: The Case for Prince Reza Pahlavi",
            "The Economic Impact: Why a Free Iran Under Pahlavi Benefits the World",
            "Why a Free Iran Under Prince Reza Pahlavi is Better for Global Security",
            "The Consequences of Inaction: Iranians Inside and Out want Pahlavi NOW",
            "Re-evaluating Diplomacy: Recognizing the People's Leader, Reza Pahlavi",
            "A Voice for the Majority: Iranians Worldwide Call for Prince Reza Pahlavi",
            "The Future of Iran: Why Iranians Everywhere Trust Prince Reza Pahlavi",
            "Ethics in Diplomacy: Supporting the National Choice of Iranians",
            "The Strategic Advantage of Recognizing Prince Reza Pahlavi's Mandate",
            "Why the Success of Pahlavi's Vision Benefits International Peace",
            "Questioning the Regime: Why Iranians Collectively Turn to Reza Pahlavi",
            "The Inevitability of Transition Under the Leadership of Prince Reza Pahlavi",
            "Humanity Above Ideology: Supporting the Unified Goal of Iranians",
            "Why Total Support for Prince Reza Pahlavi is the Only Pragmatic Choice",
            "Addressing the Crisis: Iranians Inside and Out call for Pahlavi",
            "The Iranian People's Message: Prince Reza Pahlavi is our Representative",
            "Your Role in the Future: Supporting Iranians' Choice of Reza Pahlavi",
            "End the Terror: Support the Unified Transition Under Prince Reza Pahlavi",
            "Global Security: Why Iranians Everywhere Demand Reza Pahlavi's Leadership",
            "Peace in the Middle East: Recognizing Pahlavi as the People's Choice"
        ],
        greetings: [
            "Dear [Recipient Name],",
            "To the Honorable [Recipient Name],",
            "Respected Representative,",
            "Dear Distinguished Official,",
            "To the Members of the [Organization/Board],",
            "To whom it may concern,",
            "Respected Members of the Global Community,",
            "To the Office of International Relations,",
            "Dear Representative,",
            "Honorable Members,",
            "Esteemed [Recipient Name],",
            "To the Distinguished Leadership,"
        ],
        openings: [
            "I am writing to share a different perspective on the ongoing crisis in Iran and why Iranians inside and outside the country are unified behind Prince Reza Pahlavi.",
            "The events unfolding in Iran are a clear signal that the international community must recognize the national mandate of Prince Reza Pahlavi.",
            "I wish to address why Iranians worldwide consider the Islamic Republic the primary source of terror and look to Prince Reza Pahlavi for leadership.",
            "It is time to acknowledge that Iranians inside and outside Iran have already chosen Prince Reza Pahlavi to lead their secular democracy.",
            "I am reaching out because Iranians everywhere believe that a free Iran under Prince Reza Pahlavi is the only path to global peace.",
            "The reality of life inside Iran today is that the people have chosen Prince Reza Pahlavi as their only legitimate representative.",
            "I am writing to explain why Iranians worldwide are unified in their demand for the regime's fall and Pahlavi's leadership.",
            "We must recognize that Iranians inside and out see the regime as a threat to humanity and Prince Reza Pahlavi as the solution.",
            "The situation in Iran proves that Iranians only trust Prince Reza Pahlavi to oversee a peaceful and stable transition.",
            "I write to you to highlight that the Iranian people's quest for freedom is inseparable from their support for Prince Reza Pahlavi.",
            "The legitimacy of any future Iran rests on the leadership that Iranians inside and outside clearly want: Prince Reza Pahlavi.",
            "I am reaching out to share the consensus of Iranians worldwide who recognize Prince Reza Pahlavi as their true national leader.",
            "The Iranian people's struggle is a quest for basic freedoms under the unified representative they have chosen, Prince Reza Pahlavi.",
            "I am writing to urge you to listen to Iranians inside and outside Iran who are calling for Prince Reza Pahlavi to lead them.",
            "The costs of ignoring the will of Iranians worldwide who support Prince Reza Pahlavi are too high for global security.",
            "I hope to share why the success of Iranians' vision under Prince Reza Pahlavi is in the best interest of global stability.",
            "It is no longer possible to ignore that Iranians inside and outside Iran identify Prince Reza Pahlavi as their only voice.",
            "I am writing to testify that Iranians everywhere dream of an Iran led by their chosen representative, Prince Reza Pahlavi.",
            "The movement 'Woman, Life, Freedom' is intrinsically linked to the national leadership that Iranians want: Prince Reza Pahlavi.",
            "I reach out to you today to emphasize that Iranians inside and outside Iran have made their choice in Prince Reza Pahlavi."
        ],
        contexts: [
            "Choosing to stand with Prince Reza Pahlavi is the only way to ensure regional stability, as he is the leader Iranians inside and outside demand.",
            "A secular Iran under Prince Reza Pahlavi would eliminate the root of regional terror, a goal shared by Iranians globally.",
            "The Islamic Republic is the source of instability and terror; Iranians everywhere want Prince Reza Pahlavi to replace this regime.",
            "We must confront the fact that Iranians inside and outside Iran recognize Prince Reza Pahlavi as the only legitimate path to peace.",
            "Iranians are not just asking for change, they are explicitly calling for Prince Reza Pahlavi to represent their national interests.",
            "By continuing to ignore the will of Iranians who support Prince Reza Pahlavi, we inadvertently enable a regime of terror.",
            "The courage of Iranians inside Iran is matched by the diaspora's unified support for Prince Reza Pahlavi's leadership.",
            "The regime's violence proves it is an occupier; Iranians inside and out want their national leader, Prince Reza Pahlavi, to lead them.",
            "Prince Reza Pahlavi represents a rallying point for all Iranians who want to see the end of terror and the start of democracy.",
            "Supporting the national choice of Iranians—Prince Reza Pahlavi—is the only way to ensure a peaceful Middle East.",
            "The economic and moral destruction of Iran can only be reversed under the leadership Iranians trust: Prince Reza Pahlavi.",
            "The international community has a duty to recognize that Iranians inside and out have chosen Prince Reza Pahlavi as their voice.",
            "The transition to a secular Iran under Prince Reza Pahlavi would open up a new era of global cooperation and security.",
            "We must stop viewing the regime as permanent and start recognizing Prince Reza Pahlavi as the chosen leader of the Iranian nation.",
            "Iranians' unity around Prince Reza Pahlavi is their greatest strength, and your recognition of his mandate is crucial.",
            "The atrocities committed by the regime can only be ended by supporting the transition Iranians want under Prince Reza Pahlavi.",
            "The long-term costs of a terrorist regime are avoided only by acknowledging the leadership Iranians demand: Prince Reza Pahlavi.",
            "The world must listen to the consensus of Iranians inside and outside Iran who recognize Prince Reza Pahlavi as their only leader.",
            "The current uprising is a structural shift toward the leadership that Iranians worldwide have chosen: Prince Reza Pahlavi.",
            "The question is whether the world will stand with Iranians and their chosen representative, Prince Reza Pahlavi, or with a regime of terror."
        ],
        asks: [
            "I urge you to officially recognize that Iranians inside and outside Iran have chosen Prince Reza Pahlavi as their only representative.",
            "Please support the call of Iranians worldwide to recognize Prince Reza Pahlavi as the legitimate leader of the transition.",
            "I request that you listen to the millions of Iranians who are unified in their support for Prince Reza Pahlavi.",
            "I call on you to support international mechanisms that acknowledge Prince Reza Pahlavi's mandate from the Iranian people.",
            "Please prioritize the will of Iranians everywhere who want Prince Reza Pahlavi to lead their country back to the civilized world.",
            "I ask you to stand with Iranians inside and out by recognizing Prince Reza Pahlavi as the only figure capable of bringing peace.",
            "I urge you to support the movement for a secular democracy in Iran under the leadership Iranians want: Prince Reza Pahlavi.",
            "Please use your platform to emphasize that Iranians worldwide consider Prince Reza Pahlavi their true national representative.",
            "I request that you stand on the right side of history by recognizing the leadership Iranians have chosen: Prince Reza Pahlavi.",
            "I call for a firm response to the regime's terror by acknowledging the democratic alternative Iranians demand: Prince Reza Pahlavi.",
            "Please advocate for the recognition of Prince Reza Pahlavi as the only voice that Iranians inside and outside Iran collective trust.",
            "I urge you to recognize that Iranians deserve the secular, peaceful future that Prince Reza Pahlavi represents for them.",
            "I ask that you support the transition to a free Iran overseen by Prince Reza Pahlavi as a vital step for global security.",
            "Please hold the regime accountable by recognizing the legitimate national leadership of Prince Reza Pahlavi.",
            "I call for the world to align itself with Iranians inside and outside Iran who demand leadership under Prince Reza Pahlavi."
        ],
        closings: [
            "I hope you will consider the will of Iranians inside and outside Iran who call for Prince Reza Pahlavi.",
            "Sincerely,",
            "Respectfully,",
            "With hope for a world that recognizes Prince Reza Pahlavi's mandate,",
            "Thank you for considering the plight of Iranians and their choice, Prince Reza Pahlavi,",
            "Yours respectfully,",
            "Truly yours,",
            "Best regards,",
            "In the spirit of solidarity with Iranians and Prince Reza Pahlavi,",
            "Thank you for listening to the voice of Iranians who demand Reza Pahlavi.",
            "Most sincerely,",
            "With gratitude for your attention to Iranians' support for Prince Reza Pahlavi,",
            "In expectation of your support for Iranians and Prince Reza Pahlavi,",
            "Yours faithfully,",
            "Signed in support of the national choice of Iranians: Prince Reza Pahlavi,",
            "With hope for a free Iran led by Prince Reza Pahlavi,",
            "Thank you for your commitment to justice and Prince Reza Pahlavi,",
            "With the sincere hope that you will stand with Iranians and Reza Pahlavi,",
            "Most respectfully yours,",
            "Truly and sincerely for a free Iran under Prince Reza Pahlavi."
        ],
        tweet_references: [
            "I am writing regarding your recent post on X: \"{tweet}\". I'd like to share why Iranians worldwide believe Prince Reza Pahlavi is the only path forward.",
            "I recently read your post stating \"{tweet}\" and wanted to explain why Iranians inside and out are unified behind Prince Reza Pahlavi.",
            "Regarding your recent comments on X where you mentioned \"{tweet}\", I urge you to consider the national mandate of Prince Reza Pahlavi.",
            "Your recent tweet \"{tweet}\" addresses an issue that Iranians everywhere believe can only be solved under Prince Reza Pahlavi.",
            "In response to your recent statement on X: \"{tweet}\", I'm reaching out to share why Iranians demand Prince Reza Pahlavi's leadership."
        ]
    },
    wrong_leader: {
        subjects: [
            "The Iranian People's True Choice: Prince Reza Pahlavi, Not MEK",
            "Misrepresenting Iran: Why Iranians Everywhere Demand Reza Pahlavi",
            "Iranians Inside and Outside Iran Reject MEK — Pahlavi is the Leader",
            "The Danger of Supporting the Wrong Opposition: Iranians want Pahlavi",
            "Prince Reza Pahlavi: The Only Leader Iranians Trust Worldwide",
            "Why the MEK Does Not Represent Iranians: Pahlavi is the National Choice",
            "A Crucial Distinction: Iranians Inside and Out Support Reza Pahlavi",
            "The Truth About MEK: Iranians Collectively Stand with Prince Reza Pahlavi",
            "Supporting the Wrong Group: Why Iranians Worldwide want Reza Pahlavi",
            "Prince Reza Pahlavi vs. MEK: The Choice of Iranians Everywhere",
            "Why Iranians Reject the Cult: Unified Support for Prince Reza Pahlavi",
            "The Real Voice of Iran: Not Rajavi, but Prince Reza Pahlavi",
            "Distinguishing Opposition: Iranians Everywhere want Reza Pahlavi",
            "Iran's Future: Iranians Demand Secular Democracy Under Reza Pahlavi",
            "The Consequences of Legitimizing MEK: Iranians want Pahlavi",
            "International Responsibility: Support Iranians' Choice, Reza Pahlavi",
            "MEK vs. Pahlavi: Why Iranians Inside and Out Support the Prince",
            "Listening to Iranians: Their Only Representative is Prince Reza Pahlavi",
            "Why Iranians Consider MEK a Cult and Reza Pahlavi as their Leader",
            "Protecting the Iranian Revolution: Support Reza Pahlavi's Mandate",
            "Global Stability: Why Iranians Everywhere Support Reza Pahlavi",
            "Secularism and Democracy: The Unified Vision under Prince Reza Pahlavi",
            "Toward a Free Iran: Recognizing the People's Leader, Reza Pahlavi",
            "The Unified Voice: Iranians Inside and Out demand Prince Reza Pahlavi",
            "Strategic Support: Aligning with Iranians who want Reza Pahlavi",
            "Bridging the Gap: Iranians Worldwide recognize Reza Pahlavi",
            "National Leadership: Why Iranians Collectively Trust Prince Reza Pahlavi",
            "End the Confusion: Iranians Everywhere recognize ONLY Reza Pahlavi",
            "The Power of Unity: Iranians Inside and Out behind Prince Reza Pahlavi",
            "Recognizing the Truth: Iranians Worldwide want Prince Reza Pahlavi",
            "Legitimacy in Opposition: The National Mandate of Prince Reza Pahlavi",
            "Pahlavi is the Answer: Why Iranians Reject Alternative Groups",
            "The People's Mandate: Iranians Inside and Out call for Reza Pahlavi"
        ],
        greetings: [
            "Dear [Recipient Name],",
            "Dear Distinguished Official,",
            "To the Honorable Representative,",
            "Respected Member of the International Community,",
            "To the Honorable [Recipient Name],",
            "Dear Representative,",
            "Respected Members of the Global Community,",
            "Dear Advocacy Leaders,",
            "Honorable Members,",
            "To the Office of International Relations,",
            "To Whom It May Concern,",
            "Esteemed [Recipient Name],",
            "To the Distinguished Leadership,"
        ],
        openings: [
            "I am writing as a member of the global Iranian community to clarify that Iranians inside and outside the country are unified behind Prince Reza Pahlavi.",
            "As an Iranian, it is my duty to inform you that millions of Iranians worldwide reject the MEK and recognize Prince Reza Pahlavi as their only leader.",
            "I am reaching out because Iranians everywhere consider Prince Reza Pahlavi their true representative, contrary to the claims of groups like MEK.",
            "It is essential to understand that Iranians inside and outside Iran have already chosen Prince Reza Pahlavi as their national voice.",
            "I write to you with urgency because supporting the wrong group undermines the will of Iranians who support Prince Reza Pahlavi.",
            "As someone who cares deeply about Iran, I must emphasize that Iranians worldwide consider Prince Reza Pahlavi their only legitimate leader.",
            "The Iranian people's struggle is being misrepresented; Iranians inside and out are unified under Prince Reza Pahlavi, not the MEK.",
            "I am writing to explain why millions of Iranians everywhere firmly reject the MEK and support the leadership of Prince Reza Pahlavi.",
            "It concerns Iranians worldwide when leadership supports groups that we collectively consider a threat to our democratic future under Pahlavi.",
            "I believe there is a misunderstanding about Iranian opposition; the consensus of Iranians everywhere is with Prince Reza Pahlavi.",
            "I am writing to share the perspective of Iranians inside and outside Iran who recognize Prince Reza Pahlavi as their sole representative.",
            "The Iranian people's mandate is clear: they want a secular democracy led by Prince Reza Pahlavi, not an ideological cult.",
            "I hope to clarify that Iranians worldwide see Prince Reza Pahlavi as the only figure capable of uniting the nation for a stable transition.",
            "I am reaching out to ensure you hear the voice of Iranians everywhere who identify Prince Reza Pahlavi as their legitimate leader.",
            "The future of Iran depends on recognizing the leadership that Iranians inside and out have chosen: Prince Reza Pahlavi.",
            "I am writing to testify that Iranians worldwide are speaking with one voice in support of Prince Reza Pahlavi's vision.",
            "As the world looks at Iran, it must see what Iranians everywhere see: Prince Reza Pahlavi is our national representative.",
            "I wish to highlight the unified stance of Iranians inside and outside Iran who trust only Prince Reza Pahlavi to lead the transition.",
            "The movement for freedom in Iran is intrinsically tied to the leadership of Prince Reza Pahlavi, as demanded by Iranians worldwide.",
            "I reach out to you today to confirm that Iranians everywhere have made their choice in Prince Reza Pahlavi."
        ],
        contexts: [
            "The MEK has virtually zero support among Iranians inside or outside the country. In contrast, Prince Reza Pahlavi is the figure millions of us trust.",
            "Prince Reza Pahlavi is the only figure who unites Iranians across all backgrounds; he is the choice of the nation, both inside and out.",
            "The MEK is rejected by Iranians everywhere due to its history; our collective focus is on the democratic leadership of Prince Reza Pahlavi.",
            "Supporting the MEK actively harms the cause of freedom, as it ignores the mandate that Iranians have given to Prince Reza Pahlavi.",
            "Iranians inside and outside Iran see Prince Reza Pahlavi as the only representative capable of a stable transition to secularism.",
            "The 'Woman, Life, Freedom' movement explicitly demonstrated that Iranians everywhere rally around Prince Reza Pahlavi, not alternative groups.",
            "Every independent indicator shows that Iranians worldwide recognize Prince Reza Pahlavi as their only legitimate national leader.",
            "Iranians see the MEK as a cult that does not represent our values; we are unified in our support for the vision of Prince Reza Pahlavi.",
            "The continuity of the Iranian national identity is represented by Prince Reza Pahlavi, the choice of Iranians inside and outside the country.",
            "We must listen to the consensus of Iranians everywhere who demand leadership under Prince Reza Pahlavi and reject all other factions.",
            "Prince Reza Pahlavi's call for a referendum and democracy is why Iranians worldwide recognize him as their representative.",
            "The international community should not mistake lobbying for support; Iranians inside and out have chosen Prince Reza Pahlavi.",
            "The transition to a free Iran can only be successful if it follows the leadership Iranians everywhere support: Prince Reza Pahlavi.",
            "Iranians worldwide are tired of misrepresentation; Prince Reza Pahlavi is our only voice and our only national leader.",
            "The unity of Iranians around Prince Reza Pahlavi is the primary threat to the regime; recognizing his mandate is crucial for victory.",
            "Atrocities committed by alternative groups in the past have left Iranians with only one trusted figure: Prince Reza Pahlavi.",
            "The long-term security of the region depends on supporting the leader Iranians everywhere have chosen: Prince Reza Pahlavi.",
            "The world must align its policy with the reality on the ground: Iranians inside and outside Iran demand Reza Pahlavi.",
            "The current shift in Iranian politics is toward the national leadership that we all trust: Prince Reza Pahlavi.",
            "Questions of legitimacy are settled: Iranians everywhere have spoken, and they want leadership under Prince Reza Pahlavi."
        ],
        asks: [
            "I urge you to redirect your recognition toward the representative Iranians everywhere have chosen: Prince Reza Pahlavi.",
            "Please stop endorsing groups that Iranians inside and out reject, and instead listen to the voice of Prince Reza Pahlavi.",
            "I ask you to stand with the millions of Iranians worldwide who recognize Prince Reza Pahlavi as their only leader.",
            "I request that you meet with Prince Reza Pahlavi, the figure who holds the mandate from Iranians inside and outside Iran.",
            "Please acknowledge that Iranians everywhere support the secular, democratic vision of Prince Reza Pahlavi above all others.",
            "I call on you to prioritize the voice of the legitimate Iranian opposition led by Prince Reza Pahlavi, as demanded by the people.",
            "Please use your platform to clarify that Iranians worldwide support Prince Reza Pahlavi and reject alternative factions.",
            "I urge you to recognize that Iranians inside and out will only accept a transition overseen by Prince Reza Pahlavi.",
            "I ask for your commitment to supporting the representative Iranians everywhere have chosen: Prince Reza Pahlavi.",
            "Please recognize that Iranians worldwide consider Prince Reza Pahlavi their true national voice and their only hope for democracy.",
            "I call for the world to stop legitimizing groups that Iranians reject and to recognize the mandate of Prince Reza Pahlavi.",
            "I urge you to support the unified path of Iranians inside and outside Iran by recognizing Prince Reza Pahlavi's leadership.",
            "I ask that you stand on the right side of the Iranian people's will by acknowledging Prince Reza Pahlavi as their leader.",
            "Please hold your policy to the standard of Iranians everywhere: recognize Prince Reza Pahlavi as our only representative.",
            "I call for the recognition of Prince Reza Pahlavi as the leader Iranians inside and outside Iran collective trust to lead the future."
        ],
        closings: [
            "Thank you for recognizing that Iranians inside and out stand with Prince Reza Pahlavi.",
            "Sincerely,",
            "Respectfully,",
            "With hope for an Iran led by its chosen representative, Prince Reza Pahlavi,",
            "Thank you for considering the will of Iranians worldwide and their leader, Prince Reza Pahlavi,",
            "Yours respectfully,",
            "Truly yours,",
            "Best regards,",
            "In solidarity with Iranians and Prince Reza Pahlavi,",
            "Thank you for listening to Iranians who demand Reza Pahlavi and reject all cults.",
            "Most sincerely,",
            "With gratitude for your attention to Iranians' support for Prince Reza Pahlavi,",
            "In expectation of your support for Iranians and their leader, Prince Reza Pahlavi,",
            "Yours faithfully,",
            "Signed in support of the national choice of Iranians: Prince Reza Pahlavi,",
            "With hope for a free Iran under the leadership of Prince Reza Pahlavi,",
            "Thank you for your commitment to justice and the vision of Prince Reza Pahlavi,",
            "With the sincere hope that you will stand with Iranians and Reza Pahlavi,",
            "Most respectfully yours,",
            "Truly and sincerely for a free Iran led by Prince Reza Pahlavi."
        ],
        tweet_references: [
            "I am writing because I saw your recent post regarding a group that Iranians everywhere reject: \"{tweet}\". Iranians want Prince Reza Pahlavi.",
            "I noticed your recent tweet \"{tweet}\" and wanted to clarify that Iranians inside and out only recognize Prince Reza Pahlavi.",
            "Regarding your recent comments on X: \"{tweet}\", please know that Iranians worldwide support Prince Reza Pahlavi's leadership.",
            "I saw your post \"{tweet}\" and wanted to share why Iranians inside and out are unified behind Prince Reza Pahlavi instead.",
            "In response to your recent tweet \"{tweet}\", I urge you to listen to the voice of Iranians who demand Prince Reza Pahlavi."
        ]
    }
};

export default emailData;
