const emailData = {
    // ============================================================
    // IRAN LIBERATION ADVOCATES — thank them, encourage them
    // ============================================================
    supporters: {
        subjects: [
            "Thank You for Standing with the Iranian People",
            "Your Support for Iran's Freedom Means Everything",
            "Iranians Worldwide Are Grateful for Your Advocacy",
            "Stay on the Right Side of History — Iran Needs You",
            "The Iranian People Will Never Forget Your Support",
            "Thank You — The Revolution Needs Allies Like You",
            "Iran's Liberation Is Closer Because of You",
            "Gratitude from Iranians Everywhere for Your Courage",
            "Prince Reza Pahlavi and 85 Million Iranians Thank You",
            "Your Advocacy for Iran's Freedom Is Making History",
            "The February 14 Rallies Proved Our Unity — Thank You",
            "Iran's People Count on Your Continued Support",
            "Thank You for Championing Iran's Cause",
            "Your Voice Echoes in the Hearts of Iranians",
            "Together Until Victory — Thank You from Iran's People",
            "Standing with Iran's Revolution — Thank You",
            "A Free Iran Is Coming — Thanks to Allies Like You",
            "Your Commitment to Iran Inspires Us All",
            "From Iranians Everywhere: Thank You",
            "Iran's Future Is Brighter Because You Stood Up",
            "Thank You for Hearing the Voice of Iran's People",
            "Iranians United Behind Pahlavi Are Grateful",
            "Your Support Gives Hope to Millions Inside Iran",
            "The Iranian People Will Remember Who Stood with Them",
            "Iran's Freedom Is a Shared Victory — Thank You",
            "Your Courage Gives Strength to Iran's Movement",
            "Standing Together for a Free Iran — Gratitude",
            "Thank You for Not Looking Away from Iran",
            "The Right Side of History Includes You",
            "Iran's People Cherish Your Support",
        ],
        greetings: [
            "Dear {name},",
            "Honorable {name},",
            "Respected {name},",
            "Dear Representative,",
            "Dear Senator,",
            "To the Honorable {name},",
            "Dear Friend of the Iranian People,",
            "Dear Champion of Freedom,",
            "Esteemed {name},",
            "Dear Ally of Iran's People,",
        ],
        // Opening sentences — warm, grateful, personal tone
        openings: [
            "Thank you, sincerely, for your support of the Iranian people.",
            "The Iranian people are deeply grateful for your advocacy.",
            "Your willingness to stand with 85 million Iranians will not be forgotten.",
            "Your support during this historic moment means more than words can express.",
            "On behalf of Iranians who long for freedom, I want to express heartfelt gratitude.",
            "It takes courage to support a cause when it is not always easy, and your advocacy speaks volumes.",
            "Iranians inside and outside Iran appreciate your steadfast commitment to their quest for freedom.",
            "Thank you for being a true friend of the Iranian people.",
            "Your advocacy has helped keep the world's attention on the Iranian people's struggle.",
            "The road to a free Iran has been long, but allies like you make it possible.",
            "The Iranian people recognize and deeply appreciate allies who refuse to look away.",
            "There are moments in history when standing up defines a leader's legacy — this is one of them.",
            "Every time a leader like you speaks up, it sends a message through the walls of censorship: the world is with us.",
            "Iranians everywhere — from Tehran to Toronto, from Isfahan to Los Angeles — are grateful.",
            "Thank you for being on the right side of history.",
        ],
        // Expandable sentences about: gratitude + why their support matters
        opening_extras: [
            "In a world where political courage is rare, your support stands out.",
            "Knowing that leaders like you stand with the Iranian people gives them real hope.",
            "For over four decades, the Islamic Republic has terrorized its own citizens, and your voice helps break through that darkness.",
            "The Iranian people have endured decades of oppression, and your support tells them the world has not forgotten.",
            "Your advocacy is not just a political statement — it is a lifeline for millions fighting for their future.",
            "Inside Iran, every statement of international support is heard, shared, and cherished.",
            "Freedom movements succeed when they have allies who refuse to look away — and you are one of those allies.",
            "The Iranian people have suffered greatly, and your willingness to stand with them is a source of genuine inspiration.",
            "Your voice in support of Iran's liberation reaches even into the most oppressed corners of the country.",
            "The struggle for Iran's freedom has been long, but the end is now within sight thanks to allies like you.",
        ],
        // Fact sentences about Pahlavi, Feb 14, unity
        facts_pahlavi: [
            "Iranians inside and outside Iran have clearly chosen Prince Reza Pahlavi as their national representative.",
            "The February 14 rallies in Munich, Los Angeles, and Toronto were all organized at Prince Reza Pahlavi's call, and thousands answered in each city.",
            "Every major gathering of Iranians in recent years has been at Prince Reza Pahlavi's call.",
            "Prince Reza Pahlavi represents the unified voice of Iranians worldwide.",
            "Inside Iran, despite the regime's brutal suppression, the same message echoes: the people stand behind Prince Reza Pahlavi.",
            "This is not a manufactured movement — it is the genuine will of a people who have chosen their representative.",
            "The unity of Iranians behind Prince Reza Pahlavi is rare in any political movement and undeniable in its strength.",
            "From Munich to Los Angeles to Toronto, thousands rallied on February 14 at Prince Reza Pahlavi's call — a clear national mandate.",
            "Iranians of every background — young and old, from every province — have rallied behind Prince Reza Pahlavi.",
            "The February 14 events across three continents proved that the Iranian people are organized, unified, and ready for change.",
        ],
        // Fact sentences about territorial integrity, civilian protection, people's will
        facts_principles: [
            "Iran's territorial integrity is non-negotiable — no Iranian will accept the fragmentation of their homeland.",
            "The will of the Iranian people to determine their own future government must be fully respected.",
            "Maximum care must be taken to protect civilian lives — the people of Iran have suffered enough.",
            "The Iranian people demand the right to choose their own destiny through free, democratic elections.",
            "The inviolability of Iran's territorial integrity is a core principle that unites all Iranians.",
            "Civilian protection is not a policy preference — it is a moral imperative that must guide every step forward.",
            "The people's right to shape their own government is the foundation of this movement.",
            "Iran must remain whole and undivided — territorial integrity is sacred to every Iranian.",
            "Any path forward must prioritize the safety of ordinary Iranians above all else.",
            "The Iranian people insist on full commitment to democratic self-determination.",
        ],
        // Ask sentences — warm, encouraging
        asks: [
            "Please continue walking this path with the Iranian people until they achieve their freedom.",
            "We humbly ask you to continue your advocacy and encourage your colleagues to join this cause.",
            "Please stay with the Iranian people until the end of this revolution — your consistency gives us strength.",
            "We encourage you to keep using your platform to amplify the voice of the Iranian people.",
            "Please continue to insist on civilian protection and territorial integrity in all policy discussions.",
            "We ask you to bring more of your colleagues on board — every new ally accelerates Iran's freedom.",
            "Please remain a vocal champion of the Iranian people's right to choose their own future.",
            "History will remember those who stood with the Iranian people — please continue to be one of them.",
            "We ask that you keep Iran's cause at the forefront of your advocacy.",
            "Please stand firm until Iran is free — the Iranian people need allies who will not waver.",
            "We encourage you to mention Iran in your public statements — every mention gives hope inside Iran.",
            "Please continue to recognize Prince Reza Pahlavi as the voice of the Iranian people.",
            "Your voice matters more than you know — please keep speaking for Iran's freedom.",
            "Please keep championing this cause and make sure the world does not forget Iran.",
            "We ask you to remain steadfast — the Iranian people's revolution is entering a decisive phase.",
        ],
        closings: [
            "Thank you, from the bottom of our hearts, for standing on the right side of history.",
            "With deepest gratitude and hope for a free Iran,",
            "Sincerely, with appreciation that words cannot fully express,",
            "Respectfully, and with lasting gratitude,",
            "With heartfelt thanks from Iranians who dream of freedom,",
            "Thank you for being a true friend of the Iranian people,",
            "In solidarity with the Iranian people and Prince Reza Pahlavi,",
            "With gratitude, determination, and hope,",
            "Yours respectfully,",
            "Thank you — the Iranian people's freedom will be your legacy too,",
            "Until Iran is free, we thank you for standing with us,",
            "With deep appreciation for your commitment,",
            "Most sincerely, with hope and gratitude,",
            "With respect and the promise that your support will never be forgotten,",
            "Respectfully yours, on behalf of Iranians who long for freedom,",
        ],
    },

    // ============================================================
    // GLOBAL PROGRESSIVE FIGURES — persuade respectfully
    // ============================================================
    opponents: {
        subjects: [
            "The Islamic Republic Is a Terrorist Regime — Iran's People Need You",
            "37,000 Killed in 2 Days: Please Stand with Iran's People",
            "Why Supporting Iran's People Is the True Progressive Position",
            "The Islamic Republic Has Killed American Soldiers — Please Support Iran's People",
            "Ending the Islamic Republic Serves Peace and Human Rights",
            "The Iranian People Are Asking for Your Help",
            "Supporting Iran's People Is a Moral Imperative",
            "The Iranian People Deserve Your Support",
            "The Case for Standing with 85 Million Iranians",
            "Prince Reza Pahlavi and the Iranian People's Democratic Vision",
            "The February 14 Rallies Proved Iranians Are United",
            "Why Iran's Freedom Serves Regional Security",
            "The Islamic Republic's Crimes Demand a Response",
            "Human Rights, Democracy, Civilian Protection: Iran's Demands",
            "Why Progressive Leaders Should Stand with Iran's People",
            "The Iranian People Have Chosen Democracy — Please Support Them",
            "A Free Iran Means a Safer Middle East",
            "The Islamic Republic Is the Root of Regional Instability",
            "Iran's Freedom Movement Needs Your Voice",
            "The Iranian People's Revolution Deserves Support",
            "Every Progressive Value Is Violated by the Islamic Republic",
            "The Islamic Republic Kills Its Own People — Please Help",
            "Territorial Integrity, Civilian Protection, Democracy: Iran's Demands",
            "The Moral Case for Supporting Iran's Freedom",
            "Please Listen to the Voice of 85 Million Iranians",
            "Iran's People Are Fighting for the Values You Believe In",
            "The True Threat to Peace Is the Islamic Republic",
            "Supporting Iran's People Is Supporting Human Rights",
            "The World Cannot Ignore Iran's People Any Longer",
            "Stand with Iran's People — They Need Your Courage",
        ],
        greetings: [
            "Dear {name},",
            "Honorable {name},",
            "Respected {name},",
            "Dear Representative,",
            "Dear Senator,",
            "To the Honorable {name},",
            "Dear Advocate for Justice,",
            "Dear Champion of Human Rights,",
            "Esteemed {name},",
            "Dear Leader,",
        ],
        // Opening sentences — respectful, direct, fact-based
        openings: [
            "I am writing because I believe someone who cares about human rights, as you do, should know the full truth about the Islamic Republic and what the Iranian people are asking the world to do.",
            "The Islamic Republic of Iran has killed over 37,000 people in just two days. I am writing because the Iranian people need the support of leaders who care about human rights.",
            "I understand that the situation in Iran may seem complex, but from the perspective of 85 million Iranians, it is painfully simple: they want to be free, and the Islamic Republic will not let them.",
            "The Islamic Republic has killed more civilians than most terrorist organizations in history. I am writing because the Iranian people need progressive leaders to understand this reality.",
            "I respect your commitment to peace and human rights, which is exactly why I am reaching out about the Iranian people's struggle.",
            "85 million Iranians are living under a regime that has killed tens of thousands of its own people. They need your support.",
            "Supporting the Iranian people against the Islamic Republic is not about war — it is about the most fundamental human rights.",
            "Every progressive value — human rights, democracy, women's rights, freedom of speech — is violated daily by the Islamic Republic.",
            "I am writing because I believe there is a misunderstanding that needs to be corrected: supporting Iran's people is the progressive position.",
            "The Iranian people are not asking for foreign control — they are asking for solidarity in their fight for freedom.",
            "The Islamic Republic killed over 37,000 people in 48 hours and has funded terrorists who killed American soldiers. The Iranian people want it gone.",
            "I want to be direct: the Islamic Republic is a terrorist regime by every meaningful definition, and the Iranian people deserve your support.",
        ],
        // Extra persuasion sentences
        opening_extras: [
            "This is not a simple geopolitical issue — it is a humanitarian crisis that demands moral clarity.",
            "The Iranian people have endured enough, and they are asking the world for help.",
            "The Islamic Republic has also killed hundreds of American soldiers through its proxy networks across the Middle East.",
            "It funds Hamas, Hezbollah, and the Houthis, destabilizing the entire region.",
            "This regime executes dissidents, oppresses women, persecutes minorities, and kills LGBTQ individuals.",
            "The Iranian people are fighting against everything that progressive values stand against.",
            "The regime they live under is the number one state sponsor of terrorism in the world.",
            "These are not opinions — they are documented facts about the Islamic Republic.",
            "Inside Iran, people risk their lives every day to express the same desire for freedom.",
            "Action against the Islamic Republic is not aggression against Iran — it is the liberation of 85 million people.",
        ],
        // Facts about IR crimes / terrorism / US soldiers
        facts_ir_crimes: [
            "The Islamic Republic killed over 37,000 civilians in just two days.",
            "It has executed thousands of political prisoners over four decades.",
            "It funds Hamas, Hezbollah, and the Houthis, spreading terrorism across the Middle East.",
            "It has killed hundreds of American soldiers through proxy militias in Iraq, Lebanon, and across the region.",
            "It routinely tortures dissidents and suppresses every form of free expression.",
            "It oppresses women, executes LGBTQ individuals, and persecutes religious and ethnic minorities.",
            "It is the number one state sponsor of terrorism in the world.",
            "The regime's proxy networks have destabilized entire countries across the Middle East.",
            "It has been responsible for the deaths of American service members for decades.",
            "Beyond its borders, it funds every major terrorist group in the region.",
            "This is not a government that can be reformed — it is a terrorist organization.",
            "The Islamic Republic's violence extends from its own streets to battlefields across the Middle East.",
        ],
        // Facts about Pahlavi, Feb 14, unity
        facts_pahlavi: [
            "Despite this repression, the Iranian people have organized with remarkable unity behind Prince Reza Pahlavi.",
            "The February 14 rallies in Munich, Los Angeles, and Toronto were all organized at Prince Reza Pahlavi's call.",
            "Thousands answered his call in each city, proving a genuine national mandate.",
            "Inside Iran, the same desire for change burns in every home, university, and workplace.",
            "The Iranian people have chosen Prince Reza Pahlavi as their national representative — not because anyone told them to, but because he represents their values.",
            "This is not a top-down political project — it is a grassroots movement of millions.",
            "Iranians of every background have united behind Prince Reza Pahlavi's vision for a secular, democratic Iran.",
            "The February 14 events on three continents demonstrated a level of national consensus that is rare in any movement.",
            "Inside Iran, Prince Reza Pahlavi's name is chanted in streets, written on walls, and whispered in homes.",
            "The Iranian people have proven their choice through action — in rallies, protests, and acts of courage.",
        ],
        // Facts about territorial integrity, civilian protection, people's will
        facts_principles: [
            "Iran's territorial integrity is non-negotiable — this is about removing a regime, not dividing a country.",
            "The will of the Iranian people to choose their own government must be fully respected.",
            "Maximum protection for civilian lives must be the absolute priority.",
            "The Iranian people demand the right to shape their future through free, democratic elections.",
            "No one should decide Iran's future except the Iranian people themselves.",
            "Territorial integrity is sacred to every Iranian — Iran must remain whole and undivided.",
            "Civilian protection is not a secondary consideration but the foremost priority.",
            "The people's right to self-governance is the foundation of any legitimate transition.",
            "After four decades of regime violence, the safety of ordinary Iranians must guide every step forward.",
            "Democracy is not just a Western value — it is a universal one that the Iranian people demand.",
        ],
        // Ask sentences — persuasive, respectful
        asks: [
            "I respectfully ask you to stand with the Iranian people and support their right to be free.",
            "Please use your platform to speak about the Islamic Republic's crimes and support the Iranian people's cause.",
            "We urge you to recognize that supporting Iran's people against the Islamic Republic is a humanitarian cause.",
            "Please advocate for policies that insist on civilian protection and Iran's territorial integrity.",
            "I ask you to listen to the voice of Iranians who rallied on February 14 behind Prince Reza Pahlavi.",
            "History will judge leaders by whether they stood with the oppressed — please stand with Iran's people.",
            "Please support legislation that holds the Islamic Republic accountable for its crimes against humanity.",
            "We ask you to recognize the Iranian people's choice of Prince Reza Pahlavi as their national representative.",
            "Please speak out about the tens of thousands killed by the Islamic Republic and demand accountability.",
            "We urge you to support the Iranian people's right to choose their government through free elections.",
            "Please recognize that the Islamic Republic is the source of regional instability, not the Iranian people.",
            "We ask you to be a voice for the 85 million Iranians who cannot speak freely.",
            "Please help the world understand that supporting Iran's people is supporting peace and human rights.",
            "Your voice can make a real difference for 85 million people fighting for their lives and their future.",
            "Please be on the right side of history — the Iranian people need progressive leaders to stand with them.",
        ],
        closings: [
            "The Iranian people are counting on leaders like you — please hear their voice.",
            "With deep respect and hope for your support,",
            "Sincerely, with the hope that you will stand with 85 million Iranians,",
            "Respectfully, and with urgent hope,",
            "With the belief that your sense of justice will lead you to support Iran's people,",
            "Thank you for reading this — the Iranian people truly need your voice,",
            "In the name of human rights and the will of the Iranian people,",
            "With respect, determination, and hope,",
            "Yours respectfully,",
            "The Iranian people are watching and hoping — please stand with them,",
            "With sincere hope that you will be on the right side of history,",
            "Respectfully and with great urgency,",
            "Most sincerely, with hope for justice in Iran,",
            "With deep respect and an earnest plea for Iran's people,",
            "Respectfully yours — the Iranian people need allies like you,",
        ],
    },
};

export default emailData;
