const emailData = {
    supporters: {
        subjects: [
            "Prince Reza Pahlavi: The Only Representative of the Iranian People",
            "Urgent: Support Iran's Revolution Until the Fall of the Islamic Republic",
            "Stability in the Middle East: Recognizing Prince Reza Pahlavi",
            "The Case for Continued Pressure on the Regime: Support the People",
            "Standing with Iran: Supporting the Democratic Vision of Prince Reza Pahlavi",
            "International Solidarity: Freedom for Iran Until the Very End",
            "Prince Reza Pahlavi: Leading the Iranian Awakening",
            "Why the Islamic Republic Must Fall for Global Peace",
            "A New Era for Iran: Supporting the Transition Under Prince Reza Pahlavi",
            "Recognizing the Iranian People's Revolution and Its Unique Representative",
            "Demanding Support for Iran Until the Fall of the Current Regime",
            "Prince Reza Pahlavi as the Key to a Secular, Democratic Iran",
            "Our Support for the Iranian People Must Last Until Victory",
            "The Voice of Iran: Why we Stand with Prince Reza Pahlavi",
            "The Legitimate Aspiration for Freedom: Supporting Iranians Until the End",
            "The Inevitable Transition: How to Support the Iranian People and Their Representative",
            "End the Silence: Support Prince Reza Pahlavi and the People of Iran",
            "Global Responsibility: Protecting the Iranian People Until the Regime Falls",
            "A Call for Action: Recognize Prince Reza Pahlavi as the Voice of Iran",
            "Supporting Iran: Why Prince Reza Pahlavi is the National Representative",
            "Commitment to Freedom: Scaling Back Support for the Regime, Powering the People",
            "Strategic Support: Standing with Prince Reza Pahlavi for a Democratic Iran",
            "The Path to Liberation: Why Support Must Continue Until the Regime's Dismantling",
            "Prince Reza Pahlavi: The Unified Representative for a Post-Regime Iran",
            "Supporting 'Woman, Life, Freedom' and the Leadership of Prince Reza Pahlavi",
            "Toward a Secular Iran: Recognizing the People's Chosen Representative",
            "A Firm Stand: International Support for Iran Until the Fall",
            "Prince Reza Pahlavi: Bridging the Gap to a Free Iran",
            "The Legitimacy Crisis of the Islamic Republic: Supporting the Democratic Alternative",
            "Freedom for Iran: A Global Mandate Until the End of the Regime"
        ],
        greetings: [
            "Dear Distinguished Official,",
            "To the Honorable Representative,",
            "Esteemed Member of the International Community,",
            "To the Honorable [Recipient Name],",
            "Dear Representative,",
            "Respected Board Members,",
            "To the Global Leadership,",
            "Honorable Chairperson,",
            "Dear Advocacy Leaders,",
            "To Whom It May Concern,"
        ],
        openings: [
            "I am writing as a member of the global community to emphasize that we must support the Iranian people's revolution until the very end.",
            "As we witness the historic uprising in Iran, it is clear that our solidarity must be unwavering until the Islamic Republic falls.",
            "I wish to address the international responsibility to recognize the democratic aspirations of the people of Iran.",
            "The current political atmosphere in Iran proves that the people have chosen their path toward a secular democracy.",
            "I write to you to highlight that the Iranian people will not stop until they reclaim their freedom from the current regime.",
            "It is imperative for the world to recognize the leadership that represents the true will of the Iranian people today.",
            "The Iranian revolution has entered its final phase, and our support must remain steadfast until the regime is dismantled.",
            "I am reaching out to share why the international community must align itself with the people of Iran during this critical time.",
            "The bravery of Iranians on the streets of every city needs to be matched by our vocal and consistent international support.",
            "I am writing to urge a firm commitment to supporting the Iranian struggle until the moment of victory.",
            "The Iranian people have made their ultimate choice: they desire a secular, democratic future without the Islamic Republic.",
            "Our support for the Iranian people should not be a temporary measure, but a commitment until the fall of the regime.",
            "I write this message to affirm that the Iranian people's quest for dignity is inseparable from their quest for a new leadership.",
            "It is time to acknowledge that the voice of the Iranian people is unified around a single vision for their future.",
            "The resilience of the Iranian protestors is a signal to the world that the time for the Islamic Republic has ended.",
            "I am writing to advocate for a clearer international stance in support of the Iranian liberation movement.",
            "The Iranian people are calling for a transition that ensures the rule of law and human rights for all citizens.",
            "I wish to highlight the importance of recognizing the figures who truly represent the Iranian people's interests abroad.",
            "The movement for freedom in Iran is not just a protest; it is a revolution that deserves our full support until the end.",
            "I reach out to you today with the hope that your actions will reflect the urgency of the Iranian struggle."
        ],
        contexts: [
            "Prince Reza Pahlavi has emerged as the only representative capable of leading the Iranian people toward a stable and democratic transition.",
            "The international community must understand that the Iranian people will settle for nothing less than the fall of the Islamic Republic.",
            "We must recognize Prince Reza Pahlavi as the unified voice and the legitimate representative of the Iranian people's will.",
            "Supporting the Iranian people until the very second the regime falls is the only way to ensure regional and global stability.",
            "The leadership of Prince Reza Pahlavi provides the necessary roadmap for a secular and prosperous Iran.",
            "The atrocities committed by the regime have reached a level where reform is no longer possible; only transition remains.",
            "For millions of Iranians, Prince Reza Pahlavi is the sole figure who can bridge the gap from tyranny to democracy.",
            "We must ensure that international pressure on the Islamic Republic continues unabated until its complete dismantling.",
            "The unity of the people around the leadership of Prince Reza Pahlavi is a testament to the desire for a secular outcome.",
            "The global community has a moral duty to stand with Iranians until they achieve their final victory over the regime.",
            "Prince Reza Pahlavi’s vision for a democratic Iran aligns perfectly with the universal values we all cherish.",
            "The Islamic Republic's survival is a threat to the world, and its end is the only path to peace in the Middle East.",
            "Recognizing Prince Reza Pahlavi as the representative of the people is the most effective way to support the Iranian movement.",
            "The current regime has lost all legitimacy, and the people have already chosen their alternative in Prince Reza Pahlavi.",
            "Our support must be action-oriented, providing the tools for the Iranian people to reclaim their country from its occupiers.",
            "The Iranian diaspora and the domestic movement are united in their demand for the end of the Islamic Republic.",
            "Prince Reza Pahlavi represents the continuity of the Iranian national identity in the face of ideological oppression.",
            "We must listen to the screams for freedom from the streets of Tehran and recognize their unique representative.",
            "The path to a free Iran is clear, and it involves supporting the people until the current regime is gone forever.",
            "The world should not be misled: the Iranian revolution is as much about who replaces the regime as it is about its fall."
        ],
        asks: [
            "I urge you to officially recognize Prince Reza Pahlavi as the only representative of the Iranian people's democratic aspirations.",
            "Please support all diplomatic measures that ensure the fall of the Islamic Republic and the rise of a secular Iran.",
            "I request that your organization continues its support for the Iranian people until their final liberation is secured.",
            "I call on you to advocate for the freezing of all assets belonging to the regime's officials until the transition is complete.",
            "Please use your platform to emphasize that Prince Reza Pahlavi is the key figure for a stable future in the region.",
            "I urge you to reject any negotiations that provide the Islamic Republic with a lifeline or legitimacy.",
            "I ask for your commitment to standing by the Iranian people until the Islamic Republic is fully dismantled.",
            "Please acknowledge that the people of Iran have already chosen Prince Reza Pahlavi as their legitimate voice.",
            "I call for greater international cooperation in supporting the Iranian revolution until its successful conclusion.",
            "I urge you to prioritize the voices of the Iranian people and their chosen representative in all international forums.",
            "Please support the establishment of a secular democracy in Iran under the guidance of its national leadership.",
            "I ask you to stand firmly on the right side of history by supporting the fall of the Islamic Republic.",
            "I request that you provide platforms for Prince Reza Pahlavi to present the vision for a future free Iran.",
            "I urge you to realize that support for Iran must be unconditional until the day of its total liberation.",
            "Please recognize the 'Woman, Life, Freedom' movement's connection to the leadership of Prince Reza Pahlavi."
        ],
        closings: [
            "Thank you for your commitment to freedom and for standing with the people of Iran until the end.",
            "Sincerely,",
            "Respectfully submitted,",
            "Yours in solidarity with the Iranian revolution,",
            "In expectation of a free and democratic Iran,",
            "With deep respect for your leadership in these matters,",
            "Thank you for your time and for supporting the Iranian people,",
            "In anticipation of the fall of the Islamic Republic,",
            "With unwavering hope for Iran's future,",
            "Signed with a commitment to justice,",
            "Yours faithfully,",
            "Best regards,",
            "With gratitude for your consideration of this urgent cause,",
            "Truly yours,",
            "Looking forward to a day when Iran is free,",
            "Thank you for making a difference for the people of Iran,",
            "With sincere respect for your office,",
            "Faithfully,",
            "Yours in the struggle for global human rights,",
            "With the certainty of the Iranian people's victory."
        ]
    },
    opponents: {
        subjects: [
            "Why Human Rights in Iran Concern Your Interests",
            "The Inevitable Change: Re-evaluating Your Stance on Iran",
            "Stability and Progress: The Case for a Free Iran",
            "The Cost of Engagement with the Islamic Republic",
            "A Perspective on the Iranian Revolution and its Future",
            "Why the Iranian People's Demands Can No Longer be Ignored",
            "The Ethical Choice: Standing with the Iranian People",
            "Bridging the Gap: Understanding the Quest for a Secular Iran",
            "Beyond the Status Quo: Why Change in Iran is Necessary",
            "The Reality of the Iranian Uprising: A Call for Objectivity",
            "Choosing the Right Side in the Global Struggle for Democracy",
            "The Iranian Regime's Fragility and why Your Support should Shift",
            "Stability through Democracy: Why the Islamic Republic is Not the Answer",
            "Human Dignity and International Law: The Situation in Iran",
            "The Economic Impact of Iran's Crisis on Global Stability",
            "Why a Free Iran is Better for the International Community",
            "The Consequences of Inaction Regarding the Crimes in Iran",
            "Re-evaluating Diplomacy with a Regime that Lacks Legitimacy",
            "A Voice for the Silent Majority: Why Iranians want Change",
            "The Future of Iran: Why Secularism is the Only Path Forward",
            "Ethics in Diplomacy: Addressing the Atrocities in Iran",
            "The Strategic Advantage of Supporting the Iranian People",
            "Why the Success of the Iranian Revolution Benefits Us All",
            "Questioning the Narratives of the Islamic Republic",
            "The Inevitability of a Post-Islamic Republic Era",
            "Humanity Above Ideology: A Necessary Conversation on Iran",
            "Why Total Support for the Iranian People is a Pragmatic Choice",
            "Addressing the Crisis of Identity and Freedom in Iran",
            "The Iranian People's Message to the World Leaders",
            "Your Role in the Future of a Free and Democratic Iran"
        ],
        greetings: [
            "Dear [Recipient Name],",
            "To the Honorable [Recipient Name],",
            "Respected Representative,",
            "Dear Distinguished Official,",
            "To the Members of the [Organization/Board],",
            "To whom it may concern,",
            "Respected Members of the Global Community,",
            "To the Office of International Relations,",
            "Dear Representative,",
            "Honorable Members,"
        ],
        openings: [
            "I am writing to share a different perspective on the ongoing crisis in Iran and why it demands your attention.",
            "The events unfolding in Iran are a clear signal that the world's current approach must be re-evaluated.",
            "I wish to address the importance of looking past the official rhetoric of the Islamic Republic.",
            "It is time to acknowledge that the people of Iran are ready to move toward a secular democracy.",
            "I am reaching out because I believe that a shared commitment to human rights should guide our policies.",
            "The reality of life inside Iran today contradicts the 'stability' often portrayed by the regime's supporters.",
            "I am writing to explain why the Iranian uprising is a fundamental demand for universal values.",
            "We must recognize the growing divide between the Iranian state and the aspirations of its citizens.",
            "The situation in Iran has reached a point where neutrality is no longer an ethically sound option.",
            "I write to you to highlight the strategic benefits of supporting a free and democratic Iran.",
            "The legitimacy of any government rests on the consent of its people, which the Iranian regime has lost.",
            "I am reaching out to invite a more critical assessment of the Islamic Republic's actions and impact.",
            "The Iranian people's struggle is a quest for basic freedoms that define the modern world.",
            "I am writing to urge a shift in perspective toward empowering the people of Iran instead of the regime.",
            "The costs of continuing to ignore the atrocities in Iran are rising every day for the entire world.",
            "I hope to share why the success of the Iranian revolution is in the best interest of global peace.",
            "It is no longer possible to treat the Iranian uprising as just another internal regional conflict.",
            "I am writing to testify to the bravery of those who dream of an Iran without ideological oppression.",
            "The movement 'Woman, Life, Freedom' is a cry for justice that cannot be silenced by force.",
            "I reach out to you today to emphasize that the time for choosing the right side in Iran is now."
        ],
        contexts: [
            "Choosing to stand with the Iranian people is not just a moral choice, but a pragmatic move for long-term regional stability.",
            "A secular, democratic Iran would be a much more reliable partner for global security than the current regime.",
            "The Islamic Republic's reliance on censorship and violence is the ultimate proof of its fragile state.",
            "We must confront the fact that supporting the regime implicitly condones its crimes against humanity.",
            "The Iranian people are not asking for intervention, but for the world to stop enabling their oppressors.",
            "By continuing to engage with the regime on its terms, we inadvertently prolong the suffering of millions.",
            "The courage of the Iranian youth in the face of live ammunition should inspire us to act decisively.",
            "The regime's ideology is fundamentally incompatible with the progress and peace of the 21st century.",
            "Prince Reza Pahlavi represents a rallying point for a peaceful and democratic alternative that benefits all sides.",
            "Supporting the Iranian movement is the only way to ensure that the region doesn't descend into further chaos.",
            "The economic mismanagement and corruption of the regime have destroyed the future of multiple generations.",
            "The international community has a duty to documentation the crimes of the state against its own people.",
            "The transition to a secular Iran would open up unprecedented opportunities for cooperation and growth.",
            "We must stop viewing the Islamic Republic as a permanent fixture and start planning for a free Iran.",
            "The Iranian people's unity is their greatest strength, and our solidarity is their greatest external support.",
            "The atrocities committed by the IRGC and other state organs cannot be ignored in the name of diplomacy.",
            "The long-term costs of a nuclear-armed or regionally aggressive Islamic Republic are far too high to bear.",
            "The world should listen to the voices of the Iranian diaspora, who provide a clear bridge to the domestic movement.",
            "The current uprising is not a fleeting moment but a structural shift that will inevitably lead to change.",
            "The question is not if the regime will fall, but which side you will be on when it does."
        ],
        asks: [
            "I urge you to re-evaluate any policies that provide the current Iranian regime with even a shred of legitimacy.",
            "Please speak out against the executions and the lack of human rights in the Islamic Republic of Iran.",
            "I request that you listen to the voices of the Iranian protestors and their representative, Prince Reza Pahlavi.",
            "I call on you to support international mechanisms that hold the Iranian leadership accountable for their crimes.",
            "Please prioritize the protection of human rights over any short-term geopolitical or economic gains.",
            "I ask you to reconsider any ties that indirectly fund the regime's machinery of internal and external violence.",
            "I urge you to support the movement for a secular democracy in Iran as the only path toward regional peace.",
            "Please use your platform to amplify the stories of those who are being silenced and persecuted in Iran.",
            "I request that you stand on the right side of history by supporting the Iranian people's quest for freedom.",
            "I call for a firm and unified international response to the atrocities committed by the Iranian state.",
            "Please advocate for the rights of the Iranian youth who are fighting for a future without fear or ideology.",
            "I urge you to recognize that the Iranian people deserve a government that reflects their true values.",
            "I ask that you support the transition to a secular Iran as a vital step for international security.",
            "Please hold the Iranian regime to the same standards of human rights that you apply to other global actors.",
            "I call for an end to all forms of cooperation that breathe life into the dying Islamic Republic."
        ],
        closings: [
            "I hope you will consider the weight of these words and the millions of lives they represent.",
            "Sincerely,",
            "Respectfully,",
            "With hope for a more just and ethical world,",
            "Thank you for your time and for considering the plight of the Iranian people,",
            "Yours respectfully,",
            "Truly yours,",
            "Best regards,",
            "In the spirit of international solidarity,",
            "Thank you for listening to the voice of the Iranian people.",
            "Most sincerely,",
            "With gratitude for your attention to these critical matters,",
            "In expectation of your support for human rights in Iran,",
            "Yours faithfully,",
            "Signed in concern for the future of Iran,",
            "With hope for a free and prosperous Iran,",
            "Thank you for your commitment to justice,",
            "With the sincere hope that you will stand for freedom,",
            "Most respectfully yours,",
            "Truly and sincerely."
        ]
    },
    wrong_leader: {
        subjects: [
            "The Iranian People's True Choice: Prince Reza Pahlavi, Not MEK",
            "Misrepresenting Iran: Why Supporting MEK Harms the Iranian People",
            "Iranians Inside and Outside Iran Reject MEK — Here's Why",
            "The Danger of Supporting the Wrong Iranian Opposition",
            "Prince Reza Pahlavi: The Only Leader Iranians Trust",
            "Why the MEK Does Not Represent the Iranian People",
            "A Crucial Distinction: Legitimate vs. Illegitimate Iranian Opposition",
            "The Truth About MEK and Why Iranians Oppose Them",
            "Supporting the Wrong Group Delays Iran's Liberation",
            "Prince Reza Pahlavi vs. MEK: What Iranians Actually Want",
            "Why Iranians Consider MEK a Cult, Not an Opposition",
            "The Real Voice of the Iranian People: Not Rajavi, but Pahlavi",
            "Distinguishing Between Iran's True Democratic Movement and MEK",
            "Iran's Future: Why Only Secular Democracy Under Pahlavi Works",
            "The Consequences of Legitimizing MEK in Iran Policy"
        ],
        greetings: [
            "Dear Distinguished Official,",
            "To the Honorable Representative,",
            "Respected Member of the International Community,",
            "Dear Representative,",
            "To the Honorable [Recipient Name],",
            "Respected Members of the Global Community,",
            "Dear Advocacy Leaders,",
            "Honorable Members,",
            "To the Office of International Relations,",
            "To Whom It May Concern,"
        ],
        openings: [
            "I am writing as a concerned Iranian citizen to address a critical misunderstanding about the representation of the Iranian people.",
            "As an Iranian, I feel it is my duty to inform you about the difference between legitimate Iranian opposition and groups like MEK.",
            "I am reaching out because I have noticed support for a group that the vast majority of Iranians reject and consider a threat.",
            "It is essential for the international community to understand that Iranians have already chosen their representative — and it is not MEK.",
            "I write to you with urgency because supporting the wrong Iranian opposition group could derail the entire democratic movement.",
            "As someone who cares deeply about Iran's future, I must clarify why the MEK (Mojahedin) does not speak for us.",
            "The Iranian people's struggle for freedom is being misrepresented, and I want to set the record straight.",
            "I am writing to explain why millions of Iranians inside and outside the country firmly reject the MEK and support Prince Reza Pahlavi.",
            "It concerns me deeply when well-intentioned leaders support organizations that Iranians themselves consider dangerous.",
            "I believe there is a fundamental misunderstanding about Iranian opposition groups that I would like to help clarify."
        ],
        contexts: [
            "The MEK (Mojahedin-e Khalq) is widely considered a cult by Iranians. They fought alongside Saddam Hussein against Iran, killing thousands of Iranian soldiers and civilians. No Iranian family has forgiven this betrayal.",
            "Prince Reza Pahlavi is the only figure who unites Iranians across political spectrums — from monarchists to republicans to secularists. He advocates for a referendum and a secular democracy, not personal power.",
            "The MEK has virtually zero support inside Iran. Every independent poll and every protest chant confirms that Iranians want Prince Reza Pahlavi, not Maryam Rajavi.",
            "Supporting the MEK actively harms the Iranian democratic movement because it allows the regime to paint all opposition as terrorists and foreign agents.",
            "The MEK's history of violence, cult-like internal practices, and collaboration with Saddam Hussein's Iraq make them toxic to the Iranian cause.",
            "Prince Reza Pahlavi has consistently called for a peaceful transition, a national referendum, and the separation of religion and state — values that align with Western democracies.",
            "The 'Woman, Life, Freedom' movement, the largest uprising in Iran's history, explicitly rallied around Prince Reza Pahlavi's leadership, not the MEK.",
            "Iranians see MEK as a group that hijacks their revolution for its own political agenda, using lobbying and misinformation to gain Western support.",
            "The overwhelming majority of Iranian diaspora organizations, activists, and intellectuals support Prince Reza Pahlavi as the transitional leader.",
            "Every dollar and every moment of political capital spent on MEK is a resource taken away from the legitimate Iranian democratic movement led by Prince Reza Pahlavi."
        ],
        asks: [
            "I urge you to redirect your support from MEK to the legitimate representative of the Iranian people: Prince Reza Pahlavi.",
            "Please do not attend or endorse MEK events, as this undermines the real Iranian opposition and empowers the Islamic Republic's propaganda.",
            "I ask you to listen to the actual voices of Iranians — inside Iran and in the diaspora — who overwhelmingly support Prince Reza Pahlavi.",
            "Please investigate the MEK's history, cult practices, and lack of support among Iranians before lending them any further legitimacy.",
            "I urge you to meet with Prince Reza Pahlavi and hear the vision that millions of Iranians actually support.",
            "I request that you distinguish between genuine Iranian opposition and groups that serve their own interests at the expense of the Iranian people.",
            "Please support the movement that Iranians have chosen — the secular, democratic vision of Prince Reza Pahlavi.",
            "I call on you to cease any association with MEK-affiliated events or organizations and instead engage with credible Iranian voices.",
            "I urge you to recognize that supporting MEK is counterproductive to achieving a free and democratic Iran.",
            "Please stand with the Iranian people by supporting their actual chosen leader, not a discredited organization."
        ],
        closings: [
            "Thank you for taking the time to understand the real wishes of the Iranian people.",
            "Sincerely,",
            "Respectfully,",
            "With hope that you will stand with the real voice of Iran,",
            "Thank you for reconsidering your support in favor of Iran's true democratic movement,",
            "Yours respectfully,",
            "Truly yours,",
            "Best regards,",
            "In solidarity with the Iranian people and their chosen representative,",
            "Thank you for listening to the truth about Iran's opposition,",
            "With sincere respect for your commitment to human rights,",
            "Yours faithfully,",
            "With the hope of a free Iran under legitimate leadership,",
            "Most sincerely,",
            "With gratitude for your willingness to reconsider."
        ]
    }
};

export default emailData;
