"""
Iran Policy Radar — Backend API Server

Every email is generated by LLM to be 100% unique.
Uses multiple free providers with rotation to handle thousands of requests.
No API key needed! (OpenAI optional for premium quality)

Usage:
    pip install -r requirements.txt
    python server.py
"""

import asyncio
import json
import os
import random
import re
import string
import time
from contextlib import asynccontextmanager
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

load_dotenv()


@asynccontextmanager
async def lifespan(app: FastAPI):
    if not OPENAI_API_KEY:
        _init_g4f_providers()
    yield


app = FastAPI(title="Iran Policy Radar API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
STATIC_DIR = Path(__file__).parent


class EmailRequest(BaseModel):
    person_name: str
    person_role: str
    person_email: str
    person_side: str
    topic: str
    tone: str = "formal"
    sender_name: str = ""
    sender_city: str = ""


class EmailResponse(BaseModel):
    subject: str
    body: str


# ============ Prompt Engineering ============

SYSTEM_PROMPT = """You are an expert political communications ghostwriter for the Iranian diaspora.

RULES:
1. Every email MUST be completely unique. Thousands of people email the same person — similar emails = spam.
2. Vary everything: structure, arguments, personal angle, opening, closing, length (150-350 words).
3. Sometimes use bullet points, sometimes numbered lists, sometimes pure prose.
4. Must feel like a real person wrote it. No AI clichés.
5. Return ONLY valid JSON: {"subject": "...", "body": "..."}
6. No markdown, no code blocks, no extra text outside the JSON."""

TOPIC_CONTEXT = {
    "no_war": "opposing military action / war with Iran",
    "diplomacy": "supporting diplomatic engagement with Iran",
    "sanctions": "the humanitarian impact of Iran sanctions on civilians",
    "human_rights": "supporting human rights and civil society in Iran",
    "peace": "de-escalation and preventing wider conflict",
    "regime_change": "supporting a democratic future for Iran through its people",
}

ANTIWAR_INSTRUCTION = "Recipient is ANTI-WAR Democrat. THANK them, ENCOURAGE more action, suggest legislation."

PROWAR_INSTRUCTION = (
    "Recipient is PRO-WAR Republican. Be RESPECTFUL, find COMMON GROUND, "
    "explain why war BACKFIRES, suggest smarter alternatives."
)

PERSPECTIVES = [
    "someone who left Iran as a child",
    "someone whose elderly parents live in Iran",
    "a veteran who knows the cost of war",
    "an Iranian-American doctor",
    "a student activist",
    "an entrepreneur",
    "someone who protested in Iran",
    "a worried parent",
    "a Middle East policy professor",
    "an artist",
    "someone who lost family to the regime",
    "a tech worker for internet freedom",
    "a refugee lawyer",
    "a community organizer",
    "a healthcare worker",
    "a second-generation Iranian-American",
    "a journalist",
    "a small business owner",
    "a retired teacher",
    "a software engineer",
]

STYLES = [
    "Lead with a personal anecdote, then policy argument.",
    "Start with policy, then a personal story.",
    "Open with a striking fact, then connect personally.",
    "Begin with a direct question, then build your case.",
    "Acknowledge their work first, then make your request.",
    "Lead with emotion, back with logic.",
    "Open with shared values, then your perspective.",
    "Start with what's at stake for real people.",
]


def _ref_id():
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=6))


def _build_prompt(req: EmailRequest) -> str:
    topic_desc = TOPIC_CONTEXT.get(req.topic, req.topic)
    side_instruction = (
        PROWAR_INSTRUCTION if req.person_side == "prowar" else ANTIWAR_INSTRUCTION
    )

    sender_context = ""
    if req.sender_name or req.sender_city:
        parts = []
        if req.sender_name:
            parts.append(f"Sign the email as: {req.sender_name}")
        if req.sender_city:
            parts.append(f"The sender lives in: {req.sender_city}. Mention this city naturally in the email.")
        sender_context = "\n" + "\n".join(parts)

    return f"""Write a unique email to {req.person_name} ({req.person_role}).

TOPIC: {topic_desc}
SIDE: {side_instruction}
STYLE: {random.choice(STYLES)}
PERSPECTIVE: {random.choice(PERSPECTIVES)}
LENGTH: ~{random.choice([150, 200, 250, 300])} words
{sender_context}
SEED: {_ref_id()}-{random.randint(1000, 9999)}

Return ONLY: {{"subject": "...", "body": "..."}}"""


# ============ Response Parser ============

def _parse_llm_response(content: str) -> dict:
    content = content.strip()

    if content.startswith("```"):
        content = content.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        pass

    json_match = re.search(r'\{[^{}]*"subject"[^{}]*"body"[^{}]*\}', content, re.DOTALL)
    if not json_match:
        json_match = re.search(r'\{.*\}', content, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group())
        except json.JSONDecodeError:
            pass

    lines = content.split("\n")
    subject = "Regarding Iran Policy"
    body = content
    for line in lines:
        if line.lower().startswith("subject:"):
            subject = line.split(":", 1)[1].strip()
            body = content.replace(line, "").strip()
            break

    return {"subject": subject, "body": body}


# ============ Multi-Provider g4f (rotation for rate limits) ============

G4F_PROVIDERS = []


def _init_g4f_providers():
    """Load available free g4f providers."""
    global G4F_PROVIDERS
    try:
        from g4f.Provider import PollinationsAI, Blackbox, CablyAI, Chatai

        G4F_PROVIDERS = [
            {"name": "PollinationsAI", "provider": PollinationsAI, "model": "openai", "fails": 0, "last_fail": 0},
            {"name": "Blackbox", "provider": Blackbox, "model": "blackboxai", "fails": 0, "last_fail": 0},
            {"name": "CablyAI", "provider": CablyAI, "model": "o1-mini", "fails": 0, "last_fail": 0},
            {"name": "Chatai", "provider": Chatai, "model": "gpt-4o", "fails": 0, "last_fail": 0},
        ]
    except ImportError:
        from g4f.Provider import PollinationsAI
        G4F_PROVIDERS = [
            {"name": "PollinationsAI", "provider": PollinationsAI, "model": "openai", "fails": 0, "last_fail": 0},
        ]


def _get_g4f_provider():
    """Pick best available provider (least failures, with cooldown)."""
    now = time.time()
    available = [
        p for p in G4F_PROVIDERS
        if p["fails"] < 5 or (now - p["last_fail"]) > 60
    ]
    if not available:
        for p in G4F_PROVIDERS:
            p["fails"] = 0
        available = G4F_PROVIDERS

    available.sort(key=lambda p: (p["fails"], p["last_fail"]))
    return available[0]


async def generate_with_g4f(req: EmailRequest) -> EmailResponse:
    """Generate email using g4f with provider rotation."""
    from g4f.client import Client

    if not G4F_PROVIDERS:
        _init_g4f_providers()

    prompt = _build_prompt(req)
    tried = set()
    last_error = None

    for _ in range(len(G4F_PROVIDERS)):
        prov = _get_g4f_provider()
        if prov["name"] in tried:
            continue
        tried.add(prov["name"])

        try:
            def _call(p=prov):
                client = Client(provider=p["provider"])
                return client.chat.completions.create(
                    model=p["model"],
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt},
                    ],
                )

            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(None, _call)

            content = response.choices[0].message.content
            if not content or not content.strip():
                raise ValueError("Empty response")

            result = _parse_llm_response(content)
            prov["fails"] = max(0, prov["fails"] - 1)
            return EmailResponse(subject=result["subject"], body=result["body"])

        except Exception as e:
            prov["fails"] += 1
            prov["last_fail"] = time.time()
            last_error = e
            continue

    raise last_error or ValueError("All providers failed")


# ============ Provider: OpenAI ============

async def generate_with_openai(req: EmailRequest) -> EmailResponse:
    from openai import AsyncOpenAI

    client = AsyncOpenAI(api_key=OPENAI_API_KEY)

    response = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": _build_prompt(req)},
        ],
        temperature=1.2,
        max_tokens=1000,
        frequency_penalty=0.8,
        presence_penalty=0.6,
    )

    content = response.choices[0].message.content
    result = _parse_llm_response(content)
    return EmailResponse(subject=result["subject"], body=result["body"])


# ============ API Routes ============

@app.post("/api/generate-email", response_model=EmailResponse)
async def generate_email_endpoint(req: EmailRequest):
    last_error = None
    for attempt in range(3):
        try:
            if OPENAI_API_KEY:
                return await generate_with_openai(req)
            return await generate_with_g4f(req)
        except Exception as e:
            last_error = e
            await asyncio.sleep(0.5 * (attempt + 1))

    return EmailResponse(
        subject="Generation Error — Please Try Again",
        body=f"Failed after 3 attempts.\nError: {last_error}\n\nPlease click Regenerate.",
    )


@app.get("/api/health")
async def health():
    provider = "openai" if OPENAI_API_KEY else "g4f"
    return {
        "status": "ok",
        "provider": provider,
        "g4f_providers": [p["name"] for p in G4F_PROVIDERS] if not OPENAI_API_KEY else [],
    }


# ============ Static Files & Startup ============

if __name__ == "__main__":
    import uvicorn

    app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")

    provider = "openai" if OPENAI_API_KEY else "g4f"
    print("\n  Iran Policy Radar")
    if provider == "g4f":
        _init_g4f_providers()
        names = [p["name"] for p in G4F_PROVIDERS]
        print(f"  Mode: FREE (g4f) — no API key needed!")
        print(f"  Providers: {', '.join(names)}")
        print("  Auto-rotates between providers to handle rate limits")
    else:
        print("  Mode: OpenAI gpt-4o-mini (premium)")
    print("  Server: http://localhost:8000\n")
    uvicorn.run(app, host="0.0.0.0", port=8000)
else:
    app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")
