"""
Iran Policy Radar — Backend API Server

Every email is generated by LLM to be 100% unique.
Uses multiple free providers with rotation to handle thousands of requests.
No API key needed! (OpenAI optional for premium quality)

Usage:
    pip install -r requirements.txt
    python server.py
"""

import asyncio
import json
import os
import random
import re
import string
import time
from contextlib import asynccontextmanager
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

load_dotenv()


@asynccontextmanager
async def lifespan(app: FastAPI):
    if not OPENAI_API_KEY:
        _init_g4f_providers()
    yield


app = FastAPI(title="Iran Policy Radar API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
STATIC_DIR = Path(__file__).parent


class EmailRequest(BaseModel):
    person_name: str
    person_role: str
    person_email: str
    person_side: str
    topic: str
    tone: str = "formal"
    sender_name: str = ""
    sender_city: str = ""


class EmailResponse(BaseModel):
    subject: str
    body: str


# ============ Prompt Engineering ============

SYSTEM_PROMPT = """You are an expert political communications ghostwriter for the Iranian diaspora.

CRITICAL — ANTI-SPAM: Thousands of people will email the SAME recipient. If emails look similar, they get flagged as spam and DELETED. Every email MUST be radically different in structure, vocabulary, argument order, opening style, and personal angle. Treat each email as if a completely different human wrote it.

MANDATORY THEMES — Every email MUST include ALL of these:
1. TERRITORIAL INTEGRITY: Emphasize that Iran's territorial integrity is non-negotiable and inviolable.
2. PEOPLE'S WILL: Insist on full commitment to the will of the Iranian people to determine their own future system of government.
3. CIVILIAN PROTECTION: Insist on maximum care to prevent any harm to civilians.
4. PRINCE REZA PAHLAVI: Iranians inside and outside Iran recognize Prince Reza Pahlavi as their national representative. All major gatherings have been at his call, including the February 14 rallies in Munich, Los Angeles, and Toronto.

RULES:
1. Every email MUST be completely unique. Vary structure, vocabulary, argument order, personal angle, opening, closing, length (200-400 words).
2. Randomly choose: bullet points, numbered lists, pure prose, short paragraphs, or mixed formats.
3. Must feel like a real person wrote it. No AI clichés. No generic phrases.
4. Return ONLY valid JSON: {"subject": "...", "body": "..."}
5. No markdown, no code blocks, no extra text outside the JSON.
6. NEVER start two emails the same way. Vary first sentence dramatically."""

TOPIC_CONTEXT = {
    "no_war": "the situation in Iran and the people's demand for freedom",
    "diplomacy": "supporting the Iranian people's movement for self-determination",
    "sanctions": "the Iranian people's struggle against the Islamic Republic",
    "human_rights": "human rights violations by the Islamic Republic and the people's choice of leadership",
    "peace": "lasting peace through supporting the Iranian people's chosen representative",
    "regime_change": "supporting a democratic, secular future for Iran through its people's chosen leader",
}

ANTIWAR_INSTRUCTION = """Recipient is a PROGRESSIVE figure who may oppose military action.
Your goal: CONVINCE them to support the Iranian people's cause. Key arguments:
- The Islamic Republic killed over 37,000 people in just 2 days. This is a terrorist regime by any definition.
- The IR has killed many American soldiers through its proxies over decades.
- Action against the Islamic Republic is FOR regional security and peace, not against it.
- The Iranian PEOPLE want this — it is their will, led by Prince Reza Pahlavi.
- Iran's territorial integrity will be preserved. This is about removing a terrorist regime, not attacking a nation.
- Maximum care for civilian protection is paramount.
- Be persuasive but respectful. Find common ground on human rights and civilian protection."""

PROWAR_INSTRUCTION = """Recipient is an IRAN LIBERATION ADVOCATE who supports the Iranian people.
Your goal: THANK them for standing with Iranians and encourage them to stay committed.
- Express gratitude for their support of the Iranian people's cause.
- Ask them to remain on the right side of history until the end of this revolution.
- Emphasize that Iranians inside and outside Iran are unified behind Prince Reza Pahlavi.
- Mention the February 14 rallies in Munich, Los Angeles, and Toronto as proof of unity.
- Stress territorial integrity, civilian protection, and the people's right to choose their future.
- Encourage them to continue advocating and to bring more colleagues on board."""

PERSPECTIVES = [
    "someone who left Iran as a child and remembers the fear",
    "someone whose elderly parents are trapped inside Iran",
    "a veteran who served in the Middle East and knows the IR's threat firsthand",
    "an Iranian-American doctor who treats refugees",
    "a university student who organized the Feb 14 Munich rally",
    "an entrepreneur who fled Iran after the 2009 protests",
    "someone who was imprisoned by the regime and bears the scars",
    "a worried parent with family still in Tehran",
    "a Middle East policy researcher at a think tank",
    "an Iranian artist whose work was banned by the regime",
    "someone who lost a brother to regime executions",
    "a tech worker fighting for internet freedom in Iran",
    "a refugee lawyer who helps Iranians seeking asylum",
    "a community organizer who attended the Feb 14 LA rally",
    "a nurse who volunteered during the Iran protests",
    "a second-generation Iranian-American discovering their heritage",
    "a journalist who covered the Woman Life Freedom movement",
    "a small business owner in the Iranian-American community",
    "a retired military analyst who studied IR proxy warfare",
    "a software engineer building tools for Iranian activists",
    "someone who marched in the Feb 14 Toronto rally",
    "a professor of human rights law",
    "a musician who uses art to amplify Iranian voices",
    "someone whose cousin was killed in the November 2019 massacre",
    "a political science student writing their thesis on Iran",
    "an Iranian-Canadian who organized solidarity events",
    "a grandmother who remembers Iran before the revolution",
    "a firefighter whose colleague served in the Middle East",
    "a social worker helping Iranian refugee families",
    "a teacher who educates students about Iran's history",
]

STYLES = [
    "Lead with a personal anecdote, then policy argument.",
    "Start with a hard-hitting fact about the IR's crimes, then connect personally.",
    "Open with a rhetorical question, then build your case with evidence.",
    "Begin by acknowledging their work, then make a specific request.",
    "Lead with emotion about civilian suffering, then back with policy logic.",
    "Open with shared values of democracy and freedom, then your perspective.",
    "Start with what's at stake for real people inside Iran right now.",
    "Begin with a specific date or event (like the Feb 14 rallies), then expand.",
    "Open with a quote from an Iranian inside Iran, then your argument.",
    "Start with the big picture of regional security, then narrow to Iran.",
    "Lead with a comparison to other successful liberation movements.",
    "Open with a moral argument about standing with oppressed people.",
    "Begin with gratitude, then pivot to urgency and action items.",
    "Start with a vivid scene from a protest or rally, then make your case.",
    "Open by addressing a common misconception, then correct it with facts.",
]


def _ref_id():
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=6))


EMPHASIS_ANGLES = [
    "Focus heavily on territorial integrity — make it the central theme.",
    "Lead with the February 14 rallies as proof of Pahlavi's mandate.",
    "Center the email on civilian protection and humanitarian concerns.",
    "Emphasize the democratic will of the Iranian people above all.",
    "Focus on the IR's terrorism record and threat to regional security.",
    "Highlight the unity of Iranians worldwide behind Prince Reza Pahlavi.",
    "Center on the moral imperative of supporting oppressed people.",
    "Focus on the strategic/security benefits of a free Iran.",
    "Emphasize the IR's killing of American soldiers through proxies.",
    "Lead with the 37,000+ killed and the urgency of action.",
]


def _build_prompt(req: EmailRequest) -> str:
    topic_desc = TOPIC_CONTEXT.get(req.topic, req.topic)
    side_instruction = (
        PROWAR_INSTRUCTION if req.person_side == "prowar" else ANTIWAR_INSTRUCTION
    )

    sender_context = ""
    if req.sender_name or req.sender_city:
        parts = []
        if req.sender_name:
            parts.append(f"Sign the email as: {req.sender_name}")
        if req.sender_city:
            parts.append(f"The sender lives in: {req.sender_city}. Mention this city naturally in the email.")
        sender_context = "\n" + "\n".join(parts)

    word_count = random.choice([180, 220, 260, 300, 340])
    paragraph_style = random.choice([
        "Use 3-4 short paragraphs.",
        "Use 2 longer paragraphs.",
        "Mix a short opening paragraph, bullet points, then a closing paragraph.",
        "Use 4-5 very short paragraphs for quick reading.",
        "Use one flowing paragraph with a separate closing.",
    ])

    return f"""Write a completely unique email to {req.person_name} ({req.person_role}).

CONTEXT: {topic_desc}
RECIPIENT TYPE: {side_instruction}
WRITING STYLE: {random.choice(STYLES)}
WRITER'S PERSPECTIVE: {random.choice(PERSPECTIVES)}
EMPHASIS: {random.choice(EMPHASIS_ANGLES)}
FORMAT: {paragraph_style}
LENGTH: ~{word_count} words
{sender_context}
UNIQUENESS SEED: {_ref_id()}-{random.randint(10000, 99999)}-{int(time.time() * 1000) % 100000}

REMEMBER: This email MUST be radically different from any other. Vary vocabulary, sentence structure, argument order. The recipient may receive 5000+ emails — yours must stand out.

Return ONLY: {{"subject": "...", "body": "..."}}"""


# ============ Response Parser ============

def _parse_llm_response(content: str) -> dict:
    content = content.strip()

    if content.startswith("```"):
        content = content.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        pass

    json_match = re.search(r'\{[^{}]*"subject"[^{}]*"body"[^{}]*\}', content, re.DOTALL)
    if not json_match:
        json_match = re.search(r'\{.*\}', content, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group())
        except json.JSONDecodeError:
            pass

    lines = content.split("\n")
    subject = "Regarding Iran Policy"
    body = content
    for line in lines:
        if line.lower().startswith("subject:"):
            subject = line.split(":", 1)[1].strip()
            body = content.replace(line, "").strip()
            break

    return {"subject": subject, "body": body}


# ============ Multi-Provider g4f (rotation for rate limits) ============

G4F_PROVIDERS = []


def _init_g4f_providers():
    """Load available free g4f providers."""
    global G4F_PROVIDERS
    try:
        from g4f.Provider import PollinationsAI, Blackbox, CablyAI, Chatai

        G4F_PROVIDERS = [
            {"name": "PollinationsAI", "provider": PollinationsAI, "model": "openai", "fails": 0, "last_fail": 0},
            {"name": "Blackbox", "provider": Blackbox, "model": "blackboxai", "fails": 0, "last_fail": 0},
            {"name": "CablyAI", "provider": CablyAI, "model": "o1-mini", "fails": 0, "last_fail": 0},
            {"name": "Chatai", "provider": Chatai, "model": "gpt-4o", "fails": 0, "last_fail": 0},
        ]
    except ImportError:
        from g4f.Provider import PollinationsAI
        G4F_PROVIDERS = [
            {"name": "PollinationsAI", "provider": PollinationsAI, "model": "openai", "fails": 0, "last_fail": 0},
        ]


def _get_g4f_provider():
    """Pick best available provider (least failures, with cooldown)."""
    now = time.time()
    available = [
        p for p in G4F_PROVIDERS
        if p["fails"] < 5 or (now - p["last_fail"]) > 60
    ]
    if not available:
        for p in G4F_PROVIDERS:
            p["fails"] = 0
        available = G4F_PROVIDERS

    available.sort(key=lambda p: (p["fails"], p["last_fail"]))
    return available[0]


async def generate_with_g4f(req: EmailRequest) -> EmailResponse:
    """Generate email using g4f with provider rotation."""
    from g4f.client import Client

    if not G4F_PROVIDERS:
        _init_g4f_providers()

    prompt = _build_prompt(req)
    tried = set()
    last_error = None

    for _ in range(len(G4F_PROVIDERS)):
        prov = _get_g4f_provider()
        if prov["name"] in tried:
            continue
        tried.add(prov["name"])

        try:
            def _call(p=prov):
                client = Client(provider=p["provider"])
                return client.chat.completions.create(
                    model=p["model"],
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt},
                    ],
                )

            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(None, _call)

            content = response.choices[0].message.content
            if not content or not content.strip():
                raise ValueError("Empty response")

            result = _parse_llm_response(content)
            prov["fails"] = max(0, prov["fails"] - 1)
            return EmailResponse(subject=result["subject"], body=result["body"])

        except Exception as e:
            prov["fails"] += 1
            prov["last_fail"] = time.time()
            last_error = e
            continue

    raise last_error or ValueError("All providers failed")


# ============ Provider: OpenAI ============

async def generate_with_openai(req: EmailRequest) -> EmailResponse:
    from openai import AsyncOpenAI

    client = AsyncOpenAI(api_key=OPENAI_API_KEY)

    response = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": _build_prompt(req)},
        ],
        temperature=1.2,
        max_tokens=1000,
        frequency_penalty=0.8,
        presence_penalty=0.6,
    )

    content = response.choices[0].message.content
    result = _parse_llm_response(content)
    return EmailResponse(subject=result["subject"], body=result["body"])


# ============ API Routes ============

@app.post("/api/generate-email", response_model=EmailResponse)
async def generate_email_endpoint(req: EmailRequest):
    last_error = None
    for attempt in range(3):
        try:
            if OPENAI_API_KEY:
                return await generate_with_openai(req)
            return await generate_with_g4f(req)
        except Exception as e:
            last_error = e
            await asyncio.sleep(0.5 * (attempt + 1))

    return EmailResponse(
        subject="Generation Error — Please Try Again",
        body=f"Failed after 3 attempts.\nError: {last_error}\n\nPlease click Regenerate.",
    )


@app.get("/api/health")
async def health():
    provider = "openai" if OPENAI_API_KEY else "g4f"
    return {
        "status": "ok",
        "provider": provider,
        "g4f_providers": [p["name"] for p in G4F_PROVIDERS] if not OPENAI_API_KEY else [],
    }


# ============ Static Files & Startup ============

if __name__ == "__main__":
    import uvicorn

    app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")

    provider = "openai" if OPENAI_API_KEY else "g4f"
    print("\n  Iran Policy Radar")
    if provider == "g4f":
        _init_g4f_providers()
        names = [p["name"] for p in G4F_PROVIDERS]
        print(f"  Mode: FREE (g4f) — no API key needed!")
        print(f"  Providers: {', '.join(names)}")
        print("  Auto-rotates between providers to handle rate limits")
    else:
        print("  Mode: OpenAI gpt-4o-mini (premium)")
    print("  Server: http://localhost:8000\n")
    uvicorn.run(app, host="0.0.0.0", port=8000)
else:
    app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")
